name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js environment
      uses: actions/setup-node@v4.1.0
    - name: Setup PNPM
      uses: pnpm/action-setup@v4
    - name: Install
      run: pnpm install
    - name: Prepare
      run: pnpm prepare
    - name: Build APKS
      run: pnpm build
